- app.py
Apply our version token replacement to the `*_args` setting like we currently do for the path and icon settings. This enables clients who use a wrapper to launch their DCC, take advantage of the version tokens in the `*_args` setting. And allows them to support launching multiple versions of their DCC using the `versions` setting.
> For #35869: do version token replacement in the args setting

- app.py
This is to ensure there are no PySide dll compatibility issues. By prepending the Max install root to the head of %PATH%, we emulate Maya's built-in behavior of doing the same. This protects against inadvertently loading dlls from other sources, such as `Shotgun/Python/bin`, which would otherwise be at the head of %PATH%.
> Prepends the Max install root onto %PATH%.

- python/tk_multi_launchapp/software_entity_launcher.py
For #38944, Addresses QA fix for error dialog when launching Nuke on Windows.  The None value returned from Shotgun when the Sofware entity args field is not set was being converted to a string "None" and passed on the command line to Nuke, which attempted to open it as a file.
> [minor] Set software entity args default value to "", not None

- python/tk_multi_launchapp/base_launcher.py
- python/tk_multi_launchapp/prepare_apps.py
- python/tk_multi_launchapp/software_entity_launcher.py
Initial implementation for #38957 "auto detect maya paths" and #38959 "start up tk classic at maya app launch". Adds methods to that utilize SoftwareVersion and SoftwareLauncher instances generated through the new "create_engine_launcher()" method in tk-core to do all of the heavy-lifting to launch a DCC for a specified TK engine name.
> 38957 auto detect paths

- info.yml
- python/tk_multi_launchapp/software_entity_launcher.py
Updates required to retrieve original source images uploaded for thumbnails. The primary reason for this update was to get the icons associated with Software entities to display with transparency in the project overlay widget of Desktop. The implementation attempts to handle older versions of tk-core and tk-framework-shotgunutils that may not have this feature implemented.
> For #39292, Support transparent Software entity icons

- info.yml
- python/tk_multi_launchapp/base_launcher.py
- python/tk_multi_launchapp/software_entity_launcher.py
Updates the logic in the `SoftwareEntityLauncher` class to handle icons and display names that may be overridden by `SoftwareVersion` instances returned from the engine's `scan_software()` method. Only attempt to download and cache thumbnail files retrieved from an SG Software entity.
> #40470 Update display and icon fallback logic

- info.yml
- python/tk_multi_launchapp/base_launcher.py
- python/tk_multi_launchapp/single_config_launcher.py
- python/tk_multi_launchapp/software_entity_launcher.py
Implementation to determine "group" and "group_default" values to send through the properties dictionary when registering a command with the current Toolkit engine.  If a list of versions is resolved for a launch command, the group name is derived from the associated engine and group_default will be set to True for the latest version number and False for all others. The grouping mechanism is not triggered for version-less launch commands.
> #40549 Implement registered command grouping

- python/tk_multi_launchapp/base_launcher.py
- python/tk_multi_launchapp/single_config_launcher.py
- python/tk_multi_launchapp/software_entity_launcher.py
This is connected to https://github.com/shotgunsoftware/tk-core/pull/402.
This updates the launch app to work with the tweaked interface in core.
The logic for overrides, display and icons are moved up from the engine level to the launch app level. This allowed me to simplify some of the logic for how things are displayed and overridden and I added the following to the doc string:
-----------
The following logic applies to the software entries in Shotgun:
- If all three path fields for a software entity are set to None,
the record is considered an "automatic" record and the launch app
will automatically scan for suitable entries. When automatic mode
is used, the software icon and software name defined in Shotgun are
both ignored. The versions field in shotgun can however be used to …
> #40780 Launch Interface Tweaks

- python/tk_multi_launchapp/base_launcher.py
- python/tk_multi_launchapp/software_entity_launcher.py
This PR adds a couple of features to the grouping mechanism in the app launcher:
- If no group is specified via the Software entity, use the product name. This creates smart command groups for the software scanning. For example, "Houdini", "Houdini Core", and "Houdini FX" get grouped automatically without having to specify separate SW entity entries. This feels cleaner than having one big group by default with all of the found products. 
- If the menu name (for grouped commands) starts with the group name, then remove the group name from the start of the menu name. This allows the group to be "Nuke", for example, and the menu items will only display the versions available.
**Screenshot of Software Entities**:
**Results in Desktop**:
> Improved grouping mechanism for registered commands.

- info.yml
- python/tk_multi_launchapp/software_entity_launcher.py
This setting disables any filtering-out of Software entities based on project or user restrictions. As a result, all software launchers are registered as engine commands. This is intended to be used for building a project/user agnostic cache of engine commands, as will be the case with the toolkit action menu flow.
> #41411: Adds "register_all_software" setting.

- python/tk_multi_launchapp/base_launcher.py
This removes hard coded logic to work around some shortcomings in desktop.
Instead of working around like this, let's fix the shortcomings!
When things are grouped, their titles now still show up with the full name:
This means engines which don't support grouping still work nicely.
The issue in desktop is that the recents show up with double labels:
This is an issue we can address on the desktop side instead.
> removes special grouping string logic.

- python/tk_multi_launchapp/base_launcher.py
- python/tk_multi_launchapp/util.py
This replaces logic that has now been removed from tk-shell and tk-shotgun. In those implementations, the library paths were always cleared, regardless of OS, and were never restored. That was a bad idea, and caused problems with browser integration and shell launching in some cases.
> For #43545: Clears and restores Qt library paths when on Linux.

- hooks/before_register_command.py
- info.yml
- python/tk_multi_launchapp/software_entity_launcher.py
This hook will contain a method that can use used to change the engine instance name that will be associated with the launcher command when it is registered. The use case for this will be in tk-config-default2, where we're using Software entities, but need Nuke Studio to be routed to configuration for the tk-nukestudio engine instance rather than tk-nuke, which is what is specified in the Nuke Software entity in Shotgun.
> For #44069: Adds a new hook: before_register_command.py

- python/tk_multi_launchapp/base_launcher.py
- python/tk_multi_launchapp/software_entity_launcher.py
Adding compatibility with software launchers in tk-shotgun-launchpublish required a couple of tweaks to the way the callback wrapper function works. We need to be able to pass in a file_to_open argument to the callback and have that passed through to the launch logic itself.
> For #43822: Bug fix and changes needed for tk-shotgun-launchpublish.

- info.yml
- python/tk_multi_launchapp/software_entity_launcher.py
This can be used to allow an engine instance to be configured for a given environment without a launcher existing for it. This is useful in the case of Nuke Studio, where we want to allow for context changes into certain environments, but we only want the application to be launchable from a project environment.
> For #44069: Adds a skip_engine_instances app setting.

- hooks/app_launch.py
This adds a hack to an existing hack. It's unfortunate, but it does work. Since this is in support of a legacy workflow for Flame, it's a little more livable.
> For #44763: Detects Flame launches in the case of a Software entity launch.

- hooks/app_launch.py
- hooks/before_app_launch.py
- python/tk_multi_launchapp/base_launcher.py
This changes adds the engine name to the arguments supplied to the app launch hooks. This should help ease transition from classic launch configuration to Software entities where the engine name is not available via the settings.
> #45898 Supplies the engine name to the app launch hooks

- hooks/app_launch.py
Before the fix, on Mac the launch app hook would encapsulate all passed arguments in one string, making them essentially a single argument. This fix means that the args won't be passed to the executable as one string 
Before 
given the following args:
```
"/Shotgun_Media/Big Buck Bunny/09_tree_trunk_011_COMP_001/09_tree_trunk_011_COMP_001.mov" -pyeval "print 'hello'"
```
you would get
```
open -n -a "/Applications/RV64.app" --args "\"/Shotgun_Media/Big Buck Bunny/09_tree_trunk_011_COMP_001/09_tree_trunk_011_COMP_001.mov\" -pyeval \"print 'hello'\""
```
now you get:
```
open -n -a "/Applications/RV64.app" --args "/Shotgun_Media/Big Buck Bunny/09_tree_trunk_011_COMP_001/09_tree_trunk_011_COMP_001.mov" -pyeval "print 'hello'"
```
I can see a potential for breaking existing setup here though …
> SG-12573 Fix to allow multiple arguments to be supplied to the launch app on Mac

- .pre-commit-config.yaml
- README.md
- tests/python/launchapp_test_base.py
This PR includes the actions to remove Python 2.6 support in toolkit:
- Remove python 2.6 badges
- Update setup.py to drop support for 2.6
- Update the documentation and the developer.shotgunsoftware.com doc site
> SG-20925 Formalize the deprecation of python 2.6 support in toolkit

- python/tk_multi_launchapp/base_launcher.py
* Show the user a helpful error when their app fails to launch instead of just logging a message silently
> Pop up an error dialog if launch app fails.

- python/tk_multi_launchapp/single_config_launcher.py
Within the [info.yml](https://github.com/shotgunsoftware/tk-multi-launchapp/blob/b252c37f142bb3946724480352d999afc335422e/info.yml#L132) file, the description for the `versions` key mentions `The first version in the list will be considered the 'default' version if the engine running the app supports the concept.`
However, the current code disregards this ordering and always picks the latest version as default instead in [single_config_launcher.py](https://github.com/shotgunsoftware/tk-multi-launchapp/blob/b252c37f142bb3946724480352d999afc335422e/python/tk_multi_launchapp/single_config_launcher.py#L105)
This is an issue as:
1. It does not match what the description says (unless I am misunderstanding it ?)
2. One of our use-case for declaring multiple app versions is to let some artists …
> SG-31402 Bugfix/use first version as default version

- app_specific/motionbuilder/startup/init_tank.py
Relates to shotgunsoftware/tk-motionbuilder#36
> SG-32814 Improve Experience for MoBU
